name: Test Build on freebsd (macos runner)

on:
  # Enable manual run
  workflow_dispatch:

jobs:
  build-server:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Build Server
      uses: cross-platform-actions/action@v0.21.0
      with:
        operating_system: freebsd
        architecture: x86-64
        version: '13.2'
        shell: bash
        image_url: https://github.com/MetekGame/freebsd-builder/releases/download/v0.0.2/freebsd-13.2-x86-64.qcow2
        run: |
            premake5 gmake2
            gmake config=release -j3
#            gmake -j3

    - uses: actions/upload-artifact@v4.3.1
      with:
        name: server binares
        path: |
          Out/Debug
          Out/Release
